version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Turnos

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
 
  api:
    build:
      context: ./TurnosMedicos.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
