version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: turnosDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: ./TurnosMedicos.API
      dockerfile: Dockerfile
    container_name: turnosAPI
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://turnosDB:3306/Turnos
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Turnos
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  vite_docker:
    build:
      context: ./TurnosMedicos.Cliente
      dockerfile: Dockerfile
    container_name: turnosAPP
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mysql_data:
